#!/usr/bin/php
<?php
if (php_sapi_name() !== 'cli') {
    exit;
}
require "vendor/autoload.php";

$cli = new ToolCli\Command();
$cli->registerController(['help', '--help'], new App\Command\HelpController($cli));
$cli->registerController(['gen'], new App\Command\GenController($cli));

$cli->run($argv);
